spring:
  application:
    name: turbine-amqp
server:
  port: 8989
management:
  port: 8990

eureka:
  client:
    service-url:
      # 讲客户端注册到两个高可用注册中心
      defaultZone: http://peer1:8761/eureka/,http://peer1:8761/eureka/

