spring:
  application:
    name: eureka-client
server:
  port: 2001

eureka:
  client:
    service-url:
      # 讲客户端注册到两个高可用注册中心
      defaultZone: http://peer1:8761/eureka/,http://peer1:8761/eureka/


